"""added engine_details column in worker table

Revision ID: 3f216f4e9e85
Revises: 19dc95fd0786
Create Date: 2024-11-13 15:19:14.869485

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f216f4e9e85"
down_revision: str | None = "19dc95fd0786"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workers", sa.Column("engine_details", sa.JSON(), nullable=True))
    op.add_column("tasks_details", sa.Column("custom_worker", sa.VARCHAR(), nullable=True))
    op.create_index(op.f("ix_tasks_details_custom_worker"), "tasks_details", ["custom_worker"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workers", "engine_details")
    op.drop_index(op.f("ix_tasks_details_custom_worker"), table_name="tasks_details")
    op.drop_column("tasks_details", "custom_worker")
    # ### end Alembic commands ###
