"""Added group_scope to TaskDetails

Revision ID: 47d36d6ef4d6
Revises: 6d5d0db8172a
Create Date: 2024-08-13 22:01:40.009631

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47d36d6ef4d6"
down_revision: str | None = "6d5d0db8172a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks_details", sa.Column("group_scope", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_tasks_details_group_scope"), "tasks_details", ["group_scope"], unique=False)
    op.execute("UPDATE tasks_details SET group_scope = 1 WHERE group_scope IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_details_group_scope"), table_name="tasks_details")
    op.drop_column("tasks_details", "group_scope")
    # ### end Alembic commands ###
