"""Added tasks_details.translated_input_params column

Revision ID: 4ec7ae538cfb
Revises: c37e46d13572
Create Date: 2024-09-27 20:16:36.989624

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ec7ae538cfb"
down_revision: str | None = "c37e46d13572"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks_details", sa.Column("translated_input_params", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks_details", "translated_input_params")
    # ### end Alembic commands ###
