"""Addded filename to models_install_status

Revision ID: 583fbd1f8b71
Revises: 52d98e8fd54f
Create Date: 2024-12-12 10:05:44.476559

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "583fbd1f8b71"
down_revision: str | None = "52d98e8fd54f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("models_install_status", sa.Column("filename", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("models_install_status", "filename")
    # ### end Alembic commands ###
