"""Federation tables

Revision ID: 605742bcb7d9
Revises: f11111eac1d1
Create Date: 2025-03-23 09:34:08.931055

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "605742bcb7d9"
down_revision: str | None = "f11111eac1d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "federated_instances",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("instance_name", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("url_address", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("installed_flows", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_federated_instances_enabled"), "federated_instances", ["enabled"], unique=False)
    op.create_index(op.f("ix_federated_instances_instance_name"), "federated_instances", ["instance_name"], unique=True)
    op.create_table(
        "flow_delegation_config",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("flow_name", sa.String(), nullable=False),
        sa.Column("delegation_threshold", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_flow_delegation_config_flow_name"), "flow_delegation_config", ["flow_name"], unique=True)
    op.add_column("workers", sa.Column("federated_instance_name", sa.String(), nullable=True))
    op.add_column("workers", sa.Column("empty_task_requests_count", sa.BigInteger(), nullable=True))
    op.add_column("workers", sa.Column("last_asked_tasks", sa.JSON(), nullable=True))

    op.execute("UPDATE workers SET federated_instance_name = '' WHERE federated_instance_name IS NULL")
    op.execute("UPDATE workers SET empty_task_requests_count = 0 WHERE empty_task_requests_count IS NULL")
    op.execute("UPDATE workers SET last_asked_tasks = '[]' WHERE last_asked_tasks IS NULL")
    with op.batch_alter_table("workers") as batch_op:
        batch_op.alter_column("federated_instance_name", existing_type=sa.String(), nullable=False)
        batch_op.alter_column("empty_task_requests_count", existing_type=sa.BigInteger(), nullable=False)
        batch_op.alter_column("last_asked_tasks", existing_type=sa.JSON(), nullable=False)

    op.create_index(
        op.f("ix_workers_empty_task_requests_count"), "workers", ["empty_task_requests_count"], unique=False
    )
    op.create_index(op.f("ix_workers_federated_instance_name"), "workers", ["federated_instance_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workers_federated_instance_name"), table_name="workers")
    op.drop_index(op.f("ix_workers_empty_task_requests_count"), table_name="workers")
    op.drop_column("workers", "empty_task_requests_count")
    op.drop_column("workers", "federated_instance_name")
    op.drop_column("workers", "last_asked_tasks")
    op.drop_index(op.f("ix_flow_delegation_config_flow_name"), table_name="flow_delegation_config")
    op.drop_table("flow_delegation_config")
    op.drop_index(op.f("ix_federated_instances_instance_name"), table_name="federated_instances")
    op.drop_index(op.f("ix_federated_instances_enabled"), table_name="federated_instances")
    op.drop_table("federated_instances")
    # ### end Alembic commands ###
