"""background_job_locks table

Revision ID: 7faf024d9ae0
Revises: 605742bcb7d9
Create Date: 2025-04-06 14:50:46.133126

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7faf024d9ae0"
down_revision: str | None = "605742bcb7d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "background_job_locks",
        sa.Column("job_name", sa.String(), nullable=False),
        sa.Column("worker_id", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("job_name"),
    )
    op.create_index(op.f("ix_background_job_locks_expires_at"), "background_job_locks", ["expires_at"], unique=False)
    op.create_index(op.f("ix_background_job_locks_last_run_at"), "background_job_locks", ["last_run_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_background_job_locks_last_run_at"), table_name="background_job_locks")
    op.drop_index(op.f("ix_background_job_locks_expires_at"), table_name="background_job_locks")
    op.drop_table("background_job_locks")
    # ### end Alembic commands ###
