"""Added record_expires_at field to users table

Revision ID: 8ea3dfda9f00
Revises: bb4fcc367f42
Create Date: 2025-07-04 10:00:21.342267

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ea3dfda9f00"
down_revision: str | None = "bb4fcc367f42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("record_expires_at", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_users_record_expires_at"), "users", ["record_expires_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_record_expires_at"), table_name="users")
    op.drop_column("users", "record_expires_at")
    # ### end Alembic commands ###
