"""Added hidden column to TaskDetails

Revision ID: 90b4e0fa8d34
Revises: 583fbd1f8b71
Create Date: 2025-02-09 16:46:07.790047

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90b4e0fa8d34"
down_revision: str | None = "583fbd1f8b71"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks_details", sa.Column("hidden", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks_details", "hidden")
    # ### end Alembic commands ###
