"""Removed finished_at from flows_install_status

Revision ID: a25ea01188b8
Revises: 3f216f4e9e85
Create Date: 2024-11-26 09:37:55.582543

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a25ea01188b8"
down_revision: str | None = "3f216f4e9e85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flows_install_status", "finished_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("flows_install_status", sa.Column("finished_at", sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
