"""Added pytorch_version field to workers table

Revision ID: b934056c38da
Revises: 47d36d6ef4d6
Create Date: 2024-09-17 22:30:22.221848

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b934056c38da"
down_revision: str | None = "47d36d6ef4d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workers", sa.Column("pytorch_version", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workers", "pytorch_version")
    # ### end Alembic commands ###
