"""Added mode settings to workers table

Revision ID: bb4fcc367f42
Revises: 801604a5b26a
Create Date: 2025-05-23 15:29:24.794803

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb4fcc367f42"
down_revision: str | None = "801604a5b26a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workers", sa.Column("smart_memory", sa.Boolean(), nullable=True))
    op.add_column("workers", sa.Column("cache_type", sa.String(), nullable=True))
    op.add_column("workers", sa.Column("cache_size", sa.Integer(), nullable=True))
    op.add_column("workers", sa.Column("vae_cpu", sa.Boolean(), nullable=True))
    op.add_column("workers", sa.Column("reserve_vram", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workers", "reserve_vram")
    op.drop_column("workers", "vae_cpu")
    op.drop_column("workers", "cache_size")
    op.drop_column("workers", "cache_type")
    op.drop_column("workers", "smart_memory")
    # ### end Alembic commands ###
