"""Added translated_prompt column

Revision ID: c27262c26a23
Revises: c37e46d13572
Create Date: 2024-09-23 16:54:06.567254

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27262c26a23'
down_revision: str | None = 'c37e46d13572'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_details', sa.Column('translated_prompt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks_details', 'translated_prompt')
    # ### end Alembic commands ###
