"""Added tasks priority column

Revision ID: c37e46d13572
Revises: b934056c38da
Create Date: 2024-09-20 12:06:21.154958

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c37e46d13572"
down_revision: str | None = "b934056c38da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks_details", sa.Column("priority", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_tasks_details_priority"), "tasks_details", ["priority"], unique=False)
    op.execute("UPDATE tasks_details SET priority = 0 WHERE priority IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_details_priority"), table_name="tasks_details")
    op.drop_column("tasks_details", "priority")
    # ### end Alembic commands ###
