"""Added webhook support

Revision ID: e9ac216f8caa
Revises: 6f95bcd7d7e9
Create Date: 2024-07-08 22:11:19.195848

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9ac216f8caa"
down_revision: str | None = "6f95bcd7d7e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks_details", sa.Column("webhook_url", sa.String(), nullable=True))
    op.add_column("tasks_details", sa.Column("webhook_headers", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks_details", "webhook_headers")
    op.drop_column("tasks_details", "webhook_url")
    # ### end Alembic commands ###
