version: '3'

services:
  visionatrix:
    image: visionatrix/visionatrix
    ports:
      - "8288:8288"
    working_dir: /app
    volumes:
      - ./vix_flows:/app/vix_flows
      - ./vix_models:/app/vix_models
      - ./vix_tasks_files:/app/vix_tasks_files
    environment:
      - COMFY_DEBUG=${COMFY_DEBUG}
      - VIX_HOST=${VIX_HOST}
      - VIX_PORT=${VIX_PORT}

  # TODO: Add a separate database service

  # TODO: Add a separate container for auth backend
