version: '3'

services:
  visionatrix_nvidia:
    image: visionatrix/visionatrix_nvidia
    container_name: visionatrix_nvidia
    ports:
      - "${VIX_PORT:-8288}:8288"
    working_dir: /app
    volumes:
      - ./data/flows:/app/vix_flows
      - ./data/models:/app/vix_models
      - ./data/tasks_files:/app/vix_tasks_files
    environment:
      - VIX_HOST=0.0.0.0
      - VIX_PORT=8288
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  visionatrix_amd:
    image: visionatrix/visionatrix_amd
    container_name: visionatrix_amd
    ports:
      - "${VIX_PORT:-8288}:8288"
    working_dir: /app
    volumes:
      - ./data/flows:/app/vix_flows
      - ./data/models:/app/vix_models
      - ./data/tasks_files:/app/vix_tasks_files
    environment:
      - VIX_HOST=0.0.0.0
      - VIX_PORT=8288
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri

  visionatrix_cpu:
    image: visionatrix/visionatrix_cpu
    container_name: visionatrix_cpu
    ports:
      - "${VIX_PORT:-8288}:8288"
    working_dir: /app
    volumes:
      - ./data/flows:/app/vix_flows
      - ./data/models:/app/vix_models
      - ./data/tasks_files:/app/vix_tasks_files
    environment:
      - VIX_HOST=0.0.0.0
      - VIX_PORT=8288
