name: Analysis & Coverage

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ana_cov-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  analysis:
    runs-on: macos-13
    name: Analysis

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install from source
        run: python3 -m pip install ".[dev]"

      - name: Run Analysis
        run: python3 -m pylint "ai_media_wizard/"
