name: Release Tags

on:
  workflow_dispatch:

jobs:
  release_tags:
    runs-on: ubuntu-latest
    name: Push Tags

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install from source
        run: python3 -m pip install .

      - name: Run tag repos script
        run: python3 scripts/ci/release_tag_repos.py
        env:
          GITHUB_TOKEN: ${{ secrets.VISIONATRIX_TAGS }}
