.DEFAULT_GOAL := help

.PHONY: help
help:
	@echo "Visionatrix UI development. Please use \`make <target>\` where <target> is one of"
	@echo "  dev               start a development server with ./.env.dev"
	@echo " "

.PHONY: dev
dev:
	@npx nuxi dev --dotenv ./.env.dev
